  /settings:
    get:
      summary: Get a set of global settings.
      description: >-
        A set of global Stork settings.
      operationId: getSettings
      tags:
        - Settings
      responses:
        200:
          description: A set of settings
          schema:
            $ref: "#/definitions/Settings"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"
    put:
      summary: Update settings.
      description: Update global settings.
      operationId: updateSettings
      tags:
        - Settings
      parameters:
        - name: settings
          in: body
          description: Settings set
          schema:
            $ref: '#/definitions/Settings'
      responses:
        200:
          description: Settings set
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"

  /pullers:
    get:
      summary: Get the puller statuses
      description: >-
        Returns a list of puller statuses
      operationId: getPullers
      tags:
        - Settings
      responses:
          200:
            description: A set of pullers
            schema:
              $ref: "#/definitions/Pullers"
          default:
            description: generic error response
            schema:
              $ref: "#/definitions/ApiError"

  /pullers/{id}:
    get:
      summary: Get the puller status
      description: >-
        Returns a puller status with a given ID
      operationId: getPuller
      tags:
        - Settings
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Puller ID.
      responses:
          200:
            description: A puller
            schema:
              $ref: "#/definitions/Puller"
          default:
            description: generic error response
            schema:
              $ref: "#/definitions/ApiError"